name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Release]
    types:
      - completed

jobs:
  notify-start:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook - Notify Start Deploy
        uses: tsickert/discord-webhook@v5.3.0
        continue-on-error: true
        with:
          username: "Mirasaki Development CI/CD"
          avatar-url: "https://mirasaki.dev/logo.png"
          webhook-url: ${{ secrets.DEPLOYMENT_WEBHOOK_URL }}
          embed-author-name: "Continuous Deployment by Mirasaki Development"
          embed-author-url: "https://mirasaki.dev"
          embed-author-icon-url: "https://mirasaki.dev/logo.png"
          embed-color: 14228765
          embed-title: "⬇️ @md-oss/cftools.js"
          embed-description: "⌛ Deploying **`@${{ github.repository }}`**...\n📤 Service is now temporarily unavailable."

  deploy:
    permissions:
      id-token: write
      contents: read
    name: deploy
    needs: notify-start
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Fetch Teleport binaries
      uses: teleport-actions/setup@v1
      with:
        version: 16.4.0
    - name: Fetch credentials using Machine ID
      id: auth
      uses: teleport-actions/auth@v2
      with:
        proxy: tp.mirasaki.dev:443
        token: deploy-bot
        certificate-ttl: 1h
        anonymous-telemetry: 1
    - name: SSH into Server and Prepare Environment
      run: |
        tsh ssh mirasaki-development@md01.na1.mirasaki.dev << 'ENDSSH'
          cd /var/www/cftools.js
          echo "Stashing any local changes..."
          git stash
          echo "Pulling latest changes..."
          git pull origin main
          echo "Installing development dependencies..."
          npm install
          echo "Building the project's documentation..."
          npm run build:docs
          exit
        ENDSSH
        
  notify-finish:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Discord Webhook - Notify Finish Deploy
        uses: tsickert/discord-webhook@v5.3.0
        with:
          username: "Mirasaki Development CI/CD"
          avatar-url: "https://mirasaki.dev/logo.png"
          webhook-url: ${{ secrets.DEPLOYMENT_WEBHOOK_URL }}
          embed-author-name: "Continuous Deployment by Mirasaki Development"
          embed-author-url: "https://mirasaki.dev"
          embed-author-icon-url: "https://mirasaki.dev/logo.png"
          embed-color: 9559538
          embed-title: "⬆️ @md-oss/cftools.js"
          embed-description: "✅ Finished deploying **`@${{ github.repository }}`**\n📥 [Service](https://cftools.mirasaki.dev) is back online"